### ISSUE TITLE
3d co-ordinate of simplified points

### ISSUE THREAD

**Issue by padha1317** [k-m-irfan/simplified_mediapipe_face_landmarks#1]
Hi Irfan, 

Thank you for sharing this code. 
I tried and work well. However, the simplified points only return 2 coordinates (x,y), but originally it has 3 coordinates (x,y,z). How to retrieve z coordinate? I tried to change in mpFaceSimplified.py file but didnt get z-coordinate. Can you help me with it? 

Thanks in advance.

**Comment by k-m-irfan** [comment]
You're welcome!
I made some changes, now it should give out x, y, and z coordinates.

**Comment by padha1317** [comment]
Thank you for prompt help. 
May I know, why you multiply z-dimention with width? 
Does it return original value of z-dimention (original mediapipe z-dimention without simplified) ?
Because I have seen some points have same value of z-dimention (250, 188, 9), (424, 184, 9), (278, 199, 9), (291, 264, 9)
If you can explain this, it will be really helpful. 

Thanks.

**Comment by k-m-irfan** [comment]
As per mediapipe documentation the magnitude of z uses roughly the same scale as x. You can refer this link;

https://google.github.io/mediapipe/solutions/face_mesh.html#:~:text=The%20magnitude%20of%20z%20uses%20roughly%20the%20same%20scale%20as%20x

I have successfully used this to 3d track my face, so some points having same z-coordinates must be correct i think.

**Comment by padha1317** [comment]
Yes, I check this. Thanks for the update. 
I am using this to track my RGBD value, so may be I can multiply it with the focal length of the camera as the MediaPipe document stated.

**Comment by k-m-irfan** [comment]
:thumbsup:
